
drop table if exists user;
CREATE TABLE user (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(100) NOT NULL,
	FIRSTNAME VARCHAR(100),
	LASTNAME VARCHAR(100),
	CONSTRAINT PK_CONSTRAINT_USER PRIMARY KEY (ID)
) ;
CREATE UNIQUE INDEX PRIMARY_KEY ON user (ID) ;
CREATE UNIQUE INDEX UNIQUE_USER_EMAIL ON user (EMAIL) ;

INSERT INTO user
(EMAIL, FIRSTNAME, LASTNAME)
VALUES( 'test@totodupont.com', 'toto', 'dupont');

